// Conformance against go-udx, the wire authority. The vectors are generated by
// tools/gen-vectors from go-udx's own encoder and decoder; regenerate with
//   (cd tools/gen-vectors && go run . > ../../packages/udx/test/vectors/go-v3.json)

import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  CodecError,
  ConnectionId,
  type Frame,
  FrameType,
  type Packet,
  decodePacket,
  decodeVersionNegotiation,
  encodePacket,
  encodeVersionNegotiation,
  fromHex,
  toHex
} from '../src/index.js'

interface JsonPacket {
  version: number
  destinationCid: string
  sourceCid: string
  sequence: number
  destinationStreamId: number
  sourceStreamId: number
  frames: Array<Record<string, unknown>>
}

interface Verdict { input: string, ok: boolean, reencoded?: string, unsafeU64?: boolean, lossyReason?: boolean }

const vectors = JSON.parse(readFileSync(new URL('./vectors/go-v3.json', import.meta.url), 'utf8')) as {
  generator: string
  packets: Array<{ name: string, hex: string, packet: JsonPacket }>
  versionNegotiation: Array<{ name: string, hex: string, destinationCid: string, sourceCid: string, supportedVersions: number[] }>
  truncations: Verdict[]
  fuzz: Verdict[]
}

const hexFields = new Set(['data', 'resetToken'])

function frameFromJson (j: Record<string, unknown>): Frame {
  const f: Record<string, unknown> = { ...j }
  for (const k of hexFields) if (typeof f[k] === 'string') f[k] = fromHex(f[k])
  if (typeof f.connectionId === 'string') f.connectionId = new ConnectionId(fromHex(f.connectionId))
  return f as unknown as Frame
}

function frameToJson (f: Frame): Record<string, unknown> {
  const j: Record<string, unknown> = { ...f }
  for (const [k, v] of Object.entries(j)) {
    if (v instanceof Uint8Array) j[k] = toHex(v)
    if (v instanceof ConnectionId) j[k] = v.key
  }
  return j
}

function packetFromJson (j: JsonPacket): Packet {
  return {
    version: j.version,
    destinationCid: new ConnectionId(fromHex(j.destinationCid)),
    sourceCid: new ConnectionId(fromHex(j.sourceCid)),
    sequence: j.sequence,
    destinationStreamId: j.destinationStreamId,
    sourceStreamId: j.sourceStreamId,
    frames: j.frames.map(frameFromJson)
  }
}

function packetToJson (p: Packet): JsonPacket {
  return {
    version: p.version,
    destinationCid: p.destinationCid.key,
    sourceCid: p.sourceCid.key,
    sequence: p.sequence,
    destinationStreamId: p.destinationStreamId,
    sourceStreamId: p.sourceStreamId,
    frames: p.frames.map(frameToJson)
  }
}

describe(`go-udx vectors (${vectors.generator})`, () => {
  it('covers every frame type', () => {
    const seen = new Set(vectors.packets.flatMap(v => v.packet.frames.map(f => f.type)))
    for (const t of Object.values(FrameType)) expect(seen, `frame type ${t}`).toContain(t)
  })

  describe('encode matches go-udx byte for byte', () => {
    it.each(vectors.packets.map(v => [v.name, v] as const))('%s', (_name, v) => {
      expect(toHex(encodePacket(packetFromJson(v.packet)))).toBe(v.hex)
    })
  })

  describe('decode matches go-udx field for field', () => {
    it.each(vectors.packets.map(v => [v.name, v] as const))('%s', (_name, v) => {
      expect(packetToJson(decodePacket(fromHex(v.hex)))).toEqual(v.packet)
    })
  })

  describe('version negotiation', () => {
    it.each(vectors.versionNegotiation.map(v => [v.name, v] as const))('%s', (_name, v) => {
      const encoded = encodeVersionNegotiation({
        destinationCid: new ConnectionId(fromHex(v.destinationCid)),
        sourceCid: new ConnectionId(fromHex(v.sourceCid)),
        supportedVersions: v.supportedVersions
      })
      expect(toHex(encoded)).toBe(v.hex)
      const decoded = decodeVersionNegotiation(fromHex(v.hex))
      expect(decoded.destinationCid.key).toBe(v.destinationCid)
      expect(decoded.sourceCid.key).toBe(v.sourceCid)
      expect(decoded.supportedVersions).toEqual(v.supportedVersions)
    })
  })

  // Accept/reject must agree with go-udx on arbitrary input, and an accepted
  // packet must re-encode to the same bytes go-udx produces. Two deliberate
  // differences: JS rejects u64 values above 2^53-1, and a non-UTF-8 close
  // reason can't survive a string round trip.
  function checkVerdict (v: Verdict): void {
    const input = fromHex(v.input)
    let decoded: Packet | undefined
    let error: unknown
    try {
      decoded = decodePacket(input)
    } catch (err) {
      error = err
    }
    if (error !== undefined && !(error instanceof CodecError)) throw error

    if (!v.ok) {
      expect(decoded, `go-udx rejects ${v.input}`).toBeUndefined()
      return
    }
    if (v.unsafeU64 === true) {
      expect((error as CodecError | undefined)?.kind, `u64 above 2^53 in ${v.input}`).toBe('value-out-of-range')
      return
    }
    expect(error, `go-udx accepts ${v.input}`).toBeUndefined()
    if (v.lossyReason !== true) {
      expect(toHex(encodePacket(decoded as Packet))).toBe(v.reencoded)
    }
  }

  it(`agrees on all ${vectors.truncations.length} truncated packets`, () => {
    for (const v of vectors.truncations) checkVerdict(v)
  })

  it(`agrees on all ${vectors.fuzz.length} mutated packets`, () => {
    for (const v of vectors.fuzz) checkVerdict(v)
  })
})
